version: "3"
services:
        hub:
                image: selenium/hub:latest
                ports:
                        - "4444:4444"
        chrome:
                image: selenium/node-chrome:latest
                depends_on:
                        - hub
                environment:
                        - HUB_HOST=hub
        firefox:
                image: selenium/node-firefox:latest
                shm_size: '1gb'
                depends_on:
                        - hub
                environment:
                        - HUB_HOST=hub
        mysql:
                image : mysql:latest
                restart: always
                environment:
                        MYSQL_DATABASE: 'log'
                        MYSQL_USER: 'xurten'
                        MYSQL_PASSWORD: 'root'
                        MYSQL_ROOT_PASSWORD: 'root'
                ports:
                        - '3306:3306'
                volumes:
                        - my-db:/var/lib/mysql
                depends_on:
                        - hub
        mongo:
                image : mongo:4.0.4
                ports:
                        - "27017-27019:27017-27019"
        search-module1:
                image: xurten/selenium-docker
                depends_on:
                        - chrome
                        - firefox
                environment:
                        - BROWSER=chrome
                        - HUB_HOST=hub
                        - MODULE=search-module.xml
                volumes:
                        - ./search-results-chrome-1:/usr/share/udemy/test-output
        search-module2:
                image: xurten/selenium-docker
                depends_on:
                        - chrome
                        - firefox
                environment:
                        - BROWSER=firefox
                        - HUB_HOST=hub
                        - MODULE=search-module.xml
                volumes:
                        - ./search-results-firefox-2:/usr/share/udemy/test-output                
        book-flight-module1:
                image: xurten/selenium-docker
                depends_on:
                        - chrome
                        - firefox
                environment:
                        - BROWSER=chrome
                        - HUB_HOST=hub
                        - MODULE=book-flight-module.xml
                volumes:
                        - ./book-result-chrome-1:/usr/share/udemy/test-output
        book-flight-module2:
                image: xurten/selenium-docker
                depends_on:
                        - chrome
                        - firefox
                environment:
                        - BROWSER=firefox
                        - HUB_HOST=hub
                        - MODULE=book-flight-module.xml
                volumes:
                        - ./book-result-firefox-2:/usr/share/udemy/test-output                